export const allProducts = [
  {
    name: "Yellow maize",
    weight: "50kg",
    price: "60",
    category: "Cereal",
    img: "./images/cereal/yellow maize.jpg",
    new: true,
  },
  {
    name: "White maize",
    weight: "50kg",
    price: "55",
    category: "Cereal",
    img: "./images/cereal/white maize.jpg",
  },
  {
    name: "Rice (Paddy)",
    weight: "84kg",
    price: "150",
    category: "Grain",
    img: "./images/cereal/paddy rice.jfif",
  },
  {
    name: "Groundnut",
    weight: "100kg",
    price: "35",
    category: "Peanut",
    img: "./images/cereal/groundnut.jfif",
  },
  {
    name: "Cowpea (Beans)",
    weight: "100kg",
    price: "640",
    category: "Cereal",
    img: "./images/cereal/cowpea.jfif",
  },
  {
    name: "Soybean",
    weight: "100kg",
    price: "240",
    category: "Legume",
    img: "./images/cereal/soybean.jfif",
  },
  {
    name: "Maize (OPV)",
    weight: "1kg",
    price: "3",
    category: "Seedling",
    img: "./images/cereal/opv maize.jfif",
  },
  {
    name: "Garden egg",
    weight: "1kg",
    price: "3",
    category: " Seedling",
    description: "Description: Insecticide",
    img: "./images/cereal/garden eggs.jpg",
  },
  {
    name: "Tomatoe",
    weight: "1kg",
    price: "4",
    category: "Seedling",
    img: "./images/cereal/tomato (10g 50.00).jpg",
  },
  {
    name: "Carrot",
    weight: "1kg",
    price: "4",
    category: "Vegetable",
    img: "./images/cereal/carrot 2.jfif",
  },
  {
    name: "Okra",
    weight: "1kg",
    price: "4",
    category: "Vegetable",
    img: "./images/cereal/okro.jfif",
  },
  {
    name: "Yara vita",
    weight: "1l",
    price: "30",
    category: "Agro chemical",
    description: "Liquid organic fertilizer",
    img: "./images/cereal/download.jpg",
  },
  {
    name: "Pawpaw",
    weight: "1kg",
    price: "4",
    category: "Caterory: Fruit",
    img: "./images/cereal/pawpaw 1.jfif",
    new: true,
  },
  {
    name: "Pepper",
    weight: "1oog",
    price: "6cedis",
    category: "Seedling",
    img: "./images/cereal/long pepper.jfif",
  },
  {
    name: "Quadrisem(Carrot)",
    weight: "100kg",
    price: "45",
    category: "Seedling",
    img: "./images/seedlings/carrot (100g 45.00).png",
  },
  {
    name: "Kent mango",
    weight: "50g",
    price: "50",
    category: " Friut",
    img: "./images/cereal/kent mango.jfif",
  },
  {
    name: "Palmor mango",
    weight: "50g",
    price: "50",
    category: " Fruit",
    img: "./images/cereal/palmor mango.jfif",
  },
  {
    name: "Keit mango",
    weight: "50g",
    price: "50",
    category: "Friut",
    img: "./images/cereal/keit mango.jfif",
  },
  {
    name: "(Ganga) Green pepper",
    weight: "50g",
    price: "50",
    category: " Seedling",
    img: "./images/seedlings/green pepper.jpg",
    new: true,
  },
  {
    name: "Abamet",
    weight: "250ml",
    price: "15",
    category: "Agro chemical",
    description: "Insecticide",
    img: "./images/insecticides/download (1).jpg",
  },
  {
    name: "Porselen",
    weight: "30g",
    price: "8",
    category: "Agro chemical",
    description: "Insecticide",
    img: "./images/insecticides/unnamed.jpg",
  },
  {
    name: "Away",
    weight: "250ml",
    price: "20",
    category: "Agro chemical",
    description: "Insecticide",
    img: "./images/insecticides/download (3).jpg",
  },
  {
    name: "Dresscare",
    weight: "10g",
    price: "5",
    category: "Agro chemical",
    description: "Fungicide",
    img: "./images/fungicides/dresscare.jpg",
  },
  {
    name: "Sunpyrifos",
    weight: "250ml",
    price: "12",
    category: "Agro chemical",
    description: "Insecticide",
    img: "./images/insecticides/sunpyrifos-48-EC.png",
  },

  {
    name: "Sun-kopper",
    weight: "50g",
    price: "6",
    category: "Agro chemical",
    description: "Fungicide",
    img: "./images/fungicides/Sun-Kooper.png",
    new: true,
  },
  {
    name: "nwura wura",
    weight: "100g",
    price: "8",
    category: "Agro chemical",
    description: "Fungicide",
    img: "./images/pesticides/nwura-wura.png",
  },
  {
    name: "Bon Victory",
    weight: "100g",
    price: "8",
    category: "Agro chemical",
    description: "Fungicide",
    img: "./images/fungicides/bon victory.jpg",
  },
  {
    name: "Prema(onion)",
    weight: "100g",
    price: "8",
    category: "Agro chemical",
    description: "Fungicide",
    img: "./images/cereal/onion.jpg",
  },
  {
    name: "Green pepper",
    weight: "5g",
    price: "5",
    category: "Vegetables ",
    img: "./images/cereal/green pepper 2.jfif",
  },
  {
    name: "Cassava",
    weight: "100g",
    price: "150",
    category: "tuber",
    img: "./images/cereal/cassava.jfif",
    new: true,
  },
  {
    name: "Cabbage",
    weight: "100g",
    price: "5",
    category: "Vegetable",
    img: "./images/cereal/cabbage.jfif",
  },
];
